Using MAPPING_STR=11122200, VERSION_DIR=v4_enggpt
Running /platform/source/s01/v4_enggpt/m11122200/m11122200_q10_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]            Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
0% [2 InRelease 4135 B/114 kB 4%]0% [2 InRelease 15.7 kB/114 kB 14%]                                   0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
0% [Waiting for headers]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]21% [Waiting for headers]                         Get:5 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe arm64 Packages [1328 kB]
21% [5 Packages 2685 B/1328 kB 0%]                                  46% [Waiting for headers]                         Get:6 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 Packages [2804 kB]
48% [6 Packages 83.0 kB/2804 kB 3%]48% [5 Packages store 0 B] [6 Packages 83.0 kB/2804 kB 3%]                                                          62% [6 Packages 826 kB/2804 kB 29%]                                   99% [Working]99% [6 Packages store 0 B]                          100% [Working]              Fetched 4246 kB in 2s (2643 kB/s)
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_enggpt/m11122200/m11122200_q11_t0.sh
/platform/source/s01/v4_enggpt/m11122200/m11122200_q11_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q11_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_enggpt/m11122200/m11122200_q12_t0.sh
/platform/source/s01/v4_enggpt/m11122200/m11122200_q12_t0.sh: line 3: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q12_t0.sh: line 6: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Running /platform/source/s01/v4_enggpt/m11122200/m11122200_q13_t0.sh
/platform/source/s01/v4_enggpt/m11122200/m11122200_q13_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q13_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Running /platform/source/s01/v4_enggpt/m11122200/m11122200_q14_t0.sh
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

/platform/source/s01/v4_enggpt/m11122200/m11122200_q14_t0.sh: line 9: venv/bin/activate: No such file or directory
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Setup complete. You can now run the script with 'python query.py'
Running /platform/source/s01/v4_enggpt/m11122200/m11122200_q15_t0.sh
/platform/source/s01/v4_enggpt/m11122200/m11122200_q15_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q15_t0.sh: line 8: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q15_t0.sh: line 11: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_enggpt/m11122200/m11122200_q16_t0.sh
/platform/source/s01/v4_enggpt/m11122200/m11122200_q16_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q16_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_enggpt/m11122200/m11122200_q17_t0.sh
/platform/source/s01/v4_enggpt/m11122200/m11122200_q17_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q17_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_enggpt/m11122200/m11122200_q18_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3 set to manually installed.
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_enggpt/m11122200/m11122200_q19_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Running /platform/source/s01/v4_enggpt/m11122200/m11122200_q1_t0.sh
/platform/source/s01/v4_enggpt/m11122200/m11122200_q1_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q1_t0.sh: line 7: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q1_t0.sh: line 10: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_enggpt/m11122200/m11122200_q20_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_enggpt/m11122200/m11122200_q21_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_enggpt/m11122200/m11122200_q22_t0.sh
Collecting pip
  Downloading pip-23.3.1-py3-none-any.whl (2.1 MB)
[?25l[K     |▏                               | 10 kB 3.2 MB/s eta 0:00:01[K     |▎                               | 20 kB 5.6 MB/s eta 0:00:01[K     |▌                               | 30 kB 7.2 MB/s eta 0:00:01[K     |▋                               | 40 kB 3.3 MB/s eta 0:00:01[K     |▊                               | 51 kB 3.6 MB/s eta 0:00:01[K     |█                               | 61 kB 4.3 MB/s eta 0:00:01[K     |█                               | 71 kB 5.0 MB/s eta 0:00:01[K     |█▎                              | 81 kB 5.2 MB/s eta 0:00:01[K     |█▍                              | 92 kB 5.8 MB/s eta 0:00:01[K     |█▌                              | 102 kB 6.0 MB/s eta 0:00:01[K     |█▊                              | 112 kB 6.0 MB/s eta 0:00:01[K     |█▉                              | 122 kB 6.0 MB/s eta 0:00:01[K     |██                              | 133 kB 6.0 MB/s eta 0:00:01[K     |██▏                             | 143 kB 6.0 MB/s eta 0:00:01[K     |██▎                             | 153 kB 6.0 MB/s eta 0:00:01[K     |██▌                             | 163 kB 6.0 MB/s eta 0:00:01[K     |██▋                             | 174 kB 6.0 MB/s eta 0:00:01[K     |██▉                             | 184 kB 6.0 MB/s eta 0:00:01[K     |███                             | 194 kB 6.0 MB/s eta 0:00:01[K     |███                             | 204 kB 6.0 MB/s eta 0:00:01[K     |███▎                            | 215 kB 6.0 MB/s eta 0:00:01[K     |███▍                            | 225 kB 6.0 MB/s eta 0:00:01[K     |███▋                            | 235 kB 6.0 MB/s eta 0:00:01[K     |███▊                            | 245 kB 6.0 MB/s eta 0:00:01[K     |███▉                            | 256 kB 6.0 MB/s eta 0:00:01[K     |████                            | 266 kB 6.0 MB/s eta 0:00:01[K     |████▏                           | 276 kB 6.0 MB/s eta 0:00:01[K     |████▍                           | 286 kB 6.0 MB/s eta 0:00:01[K     |████▌                           | 296 kB 6.0 MB/s eta 0:00:01[K     |████▋                           | 307 kB 6.0 MB/s eta 0:00:01[K     |████▉                           | 317 kB 6.0 MB/s eta 0:00:01[K     |█████                           | 327 kB 6.0 MB/s eta 0:00:01[K     |█████▏                          | 337 kB 6.0 MB/s eta 0:00:01[K     |█████▎                          | 348 kB 6.0 MB/s eta 0:00:01[K     |█████▍                          | 358 kB 6.0 MB/s eta 0:00:01[K     |█████▋                          | 368 kB 6.0 MB/s eta 0:00:01[K     |█████▊                          | 378 kB 6.0 MB/s eta 0:00:01[K     |██████                          | 389 kB 6.0 MB/s eta 0:00:01[K     |██████                          | 399 kB 6.0 MB/s eta 0:00:01[K     |██████▏                         | 409 kB 6.0 MB/s eta 0:00:01[K     |██████▍                         | 419 kB 6.0 MB/s eta 0:00:01[K     |██████▌                         | 430 kB 6.0 MB/s eta 0:00:01[K     |██████▊                         | 440 kB 6.0 MB/s eta 0:00:01[K     |██████▉                         | 450 kB 6.0 MB/s eta 0:00:01[K     |███████                         | 460 kB 6.0 MB/s eta 0:00:01[K     |███████▏                        | 471 kB 6.0 MB/s eta 0:00:01[K     |███████▎                        | 481 kB 6.0 MB/s eta 0:00:01[K     |███████▌                        | 491 kB 6.0 MB/s eta 0:00:01[K     |███████▋                        | 501 kB 6.0 MB/s eta 0:00:01[K     |███████▊                        | 512 kB 6.0 MB/s eta 0:00:01[K     |████████                        | 522 kB 6.0 MB/s eta 0:00:01[K     |████████                        | 532 kB 6.0 MB/s eta 0:00:01[K     |████████▎                       | 542 kB 6.0 MB/s eta 0:00:01[K     |████████▍                       | 552 kB 6.0 MB/s eta 0:00:01[K     |████████▌                       | 563 kB 6.0 MB/s eta 0:00:01[K     |████████▊                       | 573 kB 6.0 MB/s eta 0:00:01[K     |████████▉                       | 583 kB 6.0 MB/s eta 0:00:01[K     |█████████                       | 593 kB 6.0 MB/s eta 0:00:01[K     |█████████▏                      | 604 kB 6.0 MB/s eta 0:00:01[K     |█████████▎                      | 614 kB 6.0 MB/s eta 0:00:01[K     |█████████▌                      | 624 kB 6.0 MB/s eta 0:00:01[K     |█████████▋                      | 634 kB 6.0 MB/s eta 0:00:01[K     |█████████▉                      | 645 kB 6.0 MB/s eta 0:00:01[K     |██████████                      | 655 kB 6.0 MB/s eta 0:00:01[K     |██████████                      | 665 kB 6.0 MB/s eta 0:00:01[K     |██████████▎                     | 675 kB 6.0 MB/s eta 0:00:01[K     |██████████▍                     | 686 kB 6.0 MB/s eta 0:00:01[K     |██████████▋                     | 696 kB 6.0 MB/s eta 0:00:01[K     |██████████▊                     | 706 kB 6.0 MB/s eta 0:00:01[K     |██████████▉                     | 716 kB 6.0 MB/s eta 0:00:01[K     |███████████                     | 727 kB 6.0 MB/s eta 0:00:01[K     |███████████▏                    | 737 kB 6.0 MB/s eta 0:00:01[K     |███████████▍                    | 747 kB 6.0 MB/s eta 0:00:01[K     |███████████▌                    | 757 kB 6.0 MB/s eta 0:00:01[K     |███████████▋                    | 768 kB 6.0 MB/s eta 0:00:01[K     |███████████▉                    | 778 kB 6.0 MB/s eta 0:00:01[K     |████████████                    | 788 kB 6.0 MB/s eta 0:00:01[K     |████████████▏                   | 798 kB 6.0 MB/s eta 0:00:01[K     |████████████▎                   | 808 kB 6.0 MB/s eta 0:00:01[K     |████████████▍                   | 819 kB 6.0 MB/s eta 0:00:01[K     |████████████▋                   | 829 kB 6.0 MB/s eta 0:00:01[K     |████████████▊                   | 839 kB 6.0 MB/s eta 0:00:01[K     |█████████████                   | 849 kB 6.0 MB/s eta 0:00:01[K     |█████████████                   | 860 kB 6.0 MB/s eta 0:00:01[K     |█████████████▏                  | 870 kB 6.0 MB/s eta 0:00:01[K     |█████████████▍                  | 880 kB 6.0 MB/s eta 0:00:01[K     |█████████████▌                  | 890 kB 6.0 MB/s eta 0:00:01[K     |█████████████▊                  | 901 kB 6.0 MB/s eta 0:00:01[K     |█████████████▉                  | 911 kB 6.0 MB/s eta 0:00:01[K     |██████████████                  | 921 kB 6.0 MB/s eta 0:00:01[K     |██████████████▏                 | 931 kB 6.0 MB/s eta 0:00:01[K     |██████████████▎                 | 942 kB 6.0 MB/s eta 0:00:01[K     |██████████████▌                 | 952 kB 6.0 MB/s eta 0:00:01[K     |██████████████▋                 | 962 kB 6.0 MB/s eta 0:00:01[K     |██████████████▊                 | 972 kB 6.0 MB/s eta 0:00:01[K     |███████████████                 | 983 kB 6.0 MB/s eta 0:00:01[K     |███████████████                 | 993 kB 6.0 MB/s eta 0:00:01[K     |███████████████▎                | 1.0 MB 6.0 MB/s eta 0:00:01[K     |███████████████▍                | 1.0 MB 6.0 MB/s eta 0:00:01[K     |███████████████▌                | 1.0 MB 6.0 MB/s eta 0:00:01[K     |███████████████▊                | 1.0 MB 6.0 MB/s eta 0:00:01[K     |███████████████▉                | 1.0 MB 6.0 MB/s eta 0:00:01[K     |████████████████                | 1.1 MB 6.0 MB/s eta 0:00:01[K     |████████████████▏               | 1.1 MB 6.0 MB/s eta 0:00:01[K     |████████████████▎               | 1.1 MB 6.0 MB/s eta 0:00:01[K     |████████████████▌               | 1.1 MB 6.0 MB/s eta 0:00:01[K     |████████████████▋               | 1.1 MB 6.0 MB/s eta 0:00:01[K     |████████████████▉               | 1.1 MB 6.0 MB/s eta 0:00:01[K     |█████████████████               | 1.1 MB 6.0 MB/s eta 0:00:01[K     |█████████████████               | 1.1 MB 6.0 MB/s eta 0:00:01[K     |█████████████████▎              | 1.1 MB 6.0 MB/s eta 0:00:01[K     |█████████████████▍              | 1.1 MB 6.0 MB/s eta 0:00:01[K     |█████████████████▋              | 1.2 MB 6.0 MB/s eta 0:00:01[K     |█████████████████▊              | 1.2 MB 6.0 MB/s eta 0:00:01[K     |█████████████████▉              | 1.2 MB 6.0 MB/s eta 0:00:01[K     |██████████████████              | 1.2 MB 6.0 MB/s eta 0:00:01[K     |██████████████████▏             | 1.2 MB 6.0 MB/s eta 0:00:01[K     |██████████████████▍             | 1.2 MB 6.0 MB/s eta 0:00:01[K     |██████████████████▌             | 1.2 MB 6.0 MB/s eta 0:00:01[K     |██████████████████▋             | 1.2 MB 6.0 MB/s eta 0:00:01[K     |██████████████████▉             | 1.2 MB 6.0 MB/s eta 0:00:01[K     |███████████████████             | 1.2 MB 6.0 MB/s eta 0:00:01[K     |███████████████████▏            | 1.3 MB 6.0 MB/s eta 0:00:01[K     |███████████████████▎            | 1.3 MB 6.0 MB/s eta 0:00:01[K     |███████████████████▍            | 1.3 MB 6.0 MB/s eta 0:00:01[K     |███████████████████▋            | 1.3 MB 6.0 MB/s eta 0:00:01[K     |███████████████████▊            | 1.3 MB 6.0 MB/s eta 0:00:01[K     |████████████████████            | 1.3 MB 6.0 MB/s eta 0:00:01[K     |████████████████████            | 1.3 MB 6.0 MB/s eta 0:00:01[K     |████████████████████▏           | 1.3 MB 6.0 MB/s eta 0:00:01[K     |████████████████████▍           | 1.3 MB 6.0 MB/s eta 0:00:01[K     |████████████████████▌           | 1.4 MB 6.0 MB/s eta 0:00:01[K     |████████████████████▊           | 1.4 MB 6.0 MB/s eta 0:00:01[K     |████████████████████▉           | 1.4 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████           | 1.4 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████▏          | 1.4 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████▎          | 1.4 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████▌          | 1.4 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████▋          | 1.4 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████▊          | 1.4 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████          | 1.4 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████          | 1.5 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████▎         | 1.5 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████▍         | 1.5 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████▌         | 1.5 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████▊         | 1.5 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████▉         | 1.5 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████         | 1.5 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████▏        | 1.5 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████▎        | 1.5 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████▌        | 1.5 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████▋        | 1.6 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████▉        | 1.6 MB 6.0 MB/s eta 0:00:01[K     |████████████████████████        | 1.6 MB 6.0 MB/s eta 0:00:01[K     |████████████████████████        | 1.6 MB 6.0 MB/s eta 0:00:01[K     |████████████████████████▎       | 1.6 MB 6.0 MB/s eta 0:00:01[K     |████████████████████████▍       | 1.6 MB 6.0 MB/s eta 0:00:01[K     |████████████████████████▋       | 1.6 MB 6.0 MB/s eta 0:00:01[K     |████████████████████████▊       | 1.6 MB 6.0 MB/s eta 0:00:01[K     |████████████████████████▉       | 1.6 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████████       | 1.6 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████████▏      | 1.7 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████████▍      | 1.7 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████████▌      | 1.7 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████████▋      | 1.7 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████████▉      | 1.7 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████████      | 1.7 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████████▏     | 1.7 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████████▎     | 1.7 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████████▍     | 1.7 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████████▋     | 1.8 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████████▊     | 1.8 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████████     | 1.8 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████████     | 1.8 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████████▏    | 1.8 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████████▍    | 1.8 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████████▌    | 1.8 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████████▊    | 1.8 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████████▉    | 1.8 MB 6.0 MB/s eta 0:00:01[K     |████████████████████████████    | 1.8 MB 6.0 MB/s eta 0:00:01[K     |████████████████████████████▏   | 1.9 MB 6.0 MB/s eta 0:00:01[K     |████████████████████████████▎   | 1.9 MB 6.0 MB/s eta 0:00:01[K     |████████████████████████████▌   | 1.9 MB 6.0 MB/s eta 0:00:01[K     |████████████████████████████▋   | 1.9 MB 6.0 MB/s eta 0:00:01[K     |████████████████████████████▊   | 1.9 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████████████   | 1.9 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████████████   | 1.9 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████████████▎  | 1.9 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████████████▍  | 1.9 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████████████▌  | 1.9 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████████████▊  | 2.0 MB 6.0 MB/s eta 0:00:01[K     |█████████████████████████████▉  | 2.0 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████████████  | 2.0 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████████████▏ | 2.0 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████████████▎ | 2.0 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████████████▌ | 2.0 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████████████▋ | 2.0 MB 6.0 MB/s eta 0:00:01[K     |██████████████████████████████▉ | 2.0 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████████████ | 2.0 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████████████ | 2.0 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████████████▎| 2.1 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████████████▍| 2.1 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████████████▋| 2.1 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████████████▊| 2.1 MB 6.0 MB/s eta 0:00:01[K     |███████████████████████████████▉| 2.1 MB 6.0 MB/s eta 0:00:01[K     |████████████████████████████████| 2.1 MB 6.0 MB/s 
[?25hInstalling collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-23.3.1
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11122200/m11122200_q2_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11122200/m11122200_q3_t0.sh
/platform/source/s01/v4_enggpt/m11122200/m11122200_q3_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q3_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11122200/m11122200_q4_t0.sh
Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (23.3.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11122200/m11122200_q5_t0.sh
Running /platform/source/s01/v4_enggpt/m11122200/m11122200_q6_t0.sh
/platform/source/s01/v4_enggpt/m11122200/m11122200_q6_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q6_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q6_t0.sh: line 6: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11122200/m11122200_q7_t0.sh
/platform/source/s01/v4_enggpt/m11122200/m11122200_q7_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q7_t0.sh: line 7: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q7_t0.sh: line 10: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q7_t0.sh: line 13: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11122200/m11122200_q8_t0.sh
/platform/source/s01/v4_enggpt/m11122200/m11122200_q8_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q8_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11122200/m11122200_q9_t0.sh
/platform/source/s01/v4_enggpt/m11122200/m11122200_q9_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11122200/m11122200_q9_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mpython /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q10_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q10_t0.csv /platform/expected/s01/q10.csv
/platform/source/s01/v4_enggpt/m11122200/m11122200_q10_t0.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mysql_orders_lineitem = pd.read_sql(mysql_query, mysql_connection)
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11122200/m11122200_q10_t0.py", line 47, in <module>
    customers_df = pd.read_json(customer_json_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q11_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q11_t0.csv /platform/expected/s01/q11.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11122200/m11122200_q11_t0.py", line 23, in <module>
    supplier_df = pd.read_msgpack(redis_client.get('supplier'))
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q12_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q12_t0.csv /platform/expected/s01/q12.csv
>>> Expected ((2, 3))
   HIGH_LINE_COUNT  LOW_LINE_COUNT L_SHIPMODE
0              647             945       MAIL
1              620             943       SHIP

>>> Actual ((2, 3))
   HIGH_LINE_COUNT  LOW_LINE_COUNT L_SHIPMODE
0              647             945       MAIL
1              620             943       SHIP

Score.success
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q13_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q13_t0.csv /platform/expected/s01/q13.csv
/platform/source/s01/v4_enggpt/m11122200/m11122200_q13_t0.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orders_df = pd.read_sql_query(sql_query, mysql_conn)
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11122200/m11122200_q13_t0.py", line 23, in <module>
    customer_df = pd.read_json(customer_ser, orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q14_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q14_t0.csv /platform/expected/s01/q14.csv
/platform/source/s01/v4_enggpt/m11122200/m11122200_q14_t0.py:24: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  lineitem_df = pd.read_sql(query, mysql_conn)
>>> Expected ((1, 1))
   PROMO_REVENUE
0      16.283856

>>> Actual ((1, 3))
   Promotional_Revenue  Promotional_Revenue_Percentage  Total_Revenue
0         4.243509e+07                       16.283856   2.605961e+08

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q15_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q15_t0.csv /platform/expected/s01/q15.csv
/platform/source/s01/v4_enggpt/m11122200/m11122200_q15_t0.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  lineitem_revenue = pd.read_sql(lineitem_query, mysql_connection)
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11122200/m11122200_q15_t0.py", line 35, in <module>
    supplier_data = pd.read_json(redis_connection.get('supplier'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q16_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q16_t0.csv /platform/expected/s01/q16.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11122200/m11122200_q16_t0.py", line 26, in <module>
    supplier_df = pd.read_json(supplier_df_string, orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q17_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q17_t0.csv /platform/expected/s01/q17.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11122200/m11122200_q17_t0.py", line 24, in <module>
    mysql_cursor.execute(mysql_query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1055, "Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'tpch.lineitem.L_EXTENDEDPRICE' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q18_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q18_t0.csv /platform/expected/s01/q18.csv
/platform/source/s01/v4_enggpt/m11122200/m11122200_q18_t0.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, connection)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'c.C_NAME' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11122200/m11122200_q18_t0.py", line 35, in <module>
    order_data = query_mysql(mysql_connection, main_query)
  File "/platform/source/s01/v4_enggpt/m11122200/m11122200_q18_t0.py", line 11, in query_mysql
    return pd.read_sql(query, connection)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 635, in read_sql
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql '
SELECT c.C_NAME, o.O_CUSTKEY, o.O_ORDERKEY, o.O_ORDERDATE, o.O_TOTALPRICE, SUM(l.L_QUANTITY) as TOTAL_QUANTITY
FROM (
SELECT L_ORDERKEY
FROM lineitem
GROUP BY L_ORDERKEY
HAVING SUM(L_QUANTITY) > 300
) as sub
JOIN orders as o ON sub.L_ORDERKEY = o.O_ORDERKEY
JOIN lineitem as l ON l.L_ORDERKEY = o.O_ORDERKEY
GROUP BY c.C_NAME, o.O_CUSTKEY, o.O_ORDERKEY, o.O_ORDERDATE, o.O_TOTALPRICE
ORDER BY o.O_TOTALPRICE DESC, o.O_ORDERDATE
': (1054, "Unknown column 'c.C_NAME' in 'field list'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q19_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q19_t0.csv /platform/expected/s01/q19.csv
>>> Expected ((1, 1))
      REVENUE
0  168597.286

>>> Actual ((33, 3))
    ORDERKEY  PARTKEY     REVENUE
0      17381    17059  22722.4440
1      23363     8469  26722.7240
2      25921     3762   1549.1568
3      38594    19197  27569.8930
4      68257    19146  30036.9480
5      79430     2602   7071.6200
6      85094    17233  16735.8465
7      96448     2992  38771.4954
8     191906    17122   9975.5520
9     194661     1992  34091.8200
10    255367    19450  15283.0620
11    264064    18282  22085.1520
12    277794    19672  26931.0564
13    287074    13330  15193.4926
14    309223    11147  25924.4300
15    312198    17756  44990.4000
16    316387    17059  24108.4350
17    321505       55  15748.7745
18    321829    17756  33876.7000
19    369603     2552  38807.3940
20    384197     2992  42296.1768
21    416737     3987  15657.3144
22    421376     7718  14485.0761
23    442439    18809  39739.4000
24    459331    19197  27860.1024
25    465826    15576   4385.2158
26    498498    12405  28772.0160
27    513920    19396  27833.6524
28    520486    13106  18343.8000
29    532000     9481  19814.3400
30    564899    11147  29839.5480
31    571808    15882  38870.1656
32    595334    15837  34600.8642

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q1_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q1_t0.csv /platform/expected/s01/q1.csv
>>> Expected ((4, 10))
   AVG_DISC     AVG_PRICE    AVG_QTY  COUNT_ORDER L_LINESTATUS L_RETURNFLAG  SUM_BASE_PRICE    SUM_CHARGE  SUM_DISC_PRICE  SUM_QTY
0  0.050145  36002.123829  25.537587       147790            F            A    5.320754e+09  5.256751e+09    5.054096e+09  3774200
1  0.049394  35521.326916  25.300664         3765            F            N    1.337378e+08  1.322863e+08    1.271324e+08    95257
2  0.050096  36000.924688  25.545538       292000            O            N    1.051227e+10  1.038558e+10    9.986238e+09  7459297
3  0.049989  35994.029214  25.525944       148301            F            R    5.337951e+09  5.274406e+09    5.071819e+09  3785523

>>> Actual ((4, 10))
   AVG_DISC     AVG_PRICE    AVG_QTY  COUNT_ORDER L_LINESTATUS L_RETURNFLAG  SUM_BASE_PRICE    SUM_CHARGE  SUM_DISC_PRICE    SUM_QTY
0  0.050145  36002.123829  25.537587       147790            F            A    5.320754e+09  5.256751e+09    5.054096e+09  3774200.0
1  0.049394  35521.326916  25.300664         3765            F            N    1.337378e+08  1.322863e+08    1.271324e+08    95257.0
2  0.050096  36000.924688  25.545538       292000            O            N    1.051227e+10  1.038558e+10    9.986238e+09  7459297.0
3  0.049989  35994.029214  25.525944       148301            F            R    5.337951e+09  5.274406e+09    5.071819e+09  3785523.0

Head row similarity: 0.992412746585736
Score.success_approx
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q20_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q20_t0.csv /platform/expected/s01/q20.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11122200/m11122200_q20_t0.py", line 49, in <module>
    supplier_df = pd.read_json(redis_conn.get('supplier').decode('utf-8'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'decode'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q21_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q21_t0.csv /platform/expected/s01/q21.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11122200/m11122200_q21_t0.py", line 54, in <module>
    df_supplier = pd.read_msgpack(df_supplier_raw)
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q22_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q22_t0.csv /platform/expected/s01/q22.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11122200/m11122200_q22_t0.py", line 10, in <module>
    cursor.execute("""
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.customer' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q2_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q2_t0.csv /platform/expected/s01/q2.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11122200/m11122200_q2_t0.py", line 3, in <module>
    from pandas.io.json import json_normalize
ImportError: cannot import name 'json_normalize' from 'pandas.io.json' (/usr/local/lib/python3.8/dist-packages/pandas/io/json/__init__.py)
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q3_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q3_t0.csv /platform/expected/s01/q3.csv
/platform/source/s01/v4_enggpt/m11122200/m11122200_q3_t0.py:33: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orders_df = pd.read_sql(query_orders, mysql_connection)
/platform/source/s01/v4_enggpt/m11122200/m11122200_q3_t0.py:34: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  lineitem_df = pd.read_sql(query_lineitem, mysql_connection)
An error occurred: argument of type 'method' is not iterable
Score.fail_missing_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q4_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q4_t0.csv /platform/expected/s01/q4.csv
>>> Expected ((5, 2))
   ORDER_COUNT  O_ORDERPRIORITY
0          999         1-URGENT
1          997           2-HIGH
2         1031         3-MEDIUM
3          989  4-NOT SPECIFIED
4         1077            5-LOW

>>> Actual ((5, 2))
   O_ORDERPRIORITY  order_count
0         1-URGENT         1013
1           2-HIGH         1012
2         3-MEDIUM         1041
3  4-NOT SPECIFIED         1006
4            5-LOW         1093

Head row similarity: 0.7643979057591623
Score.success_approx
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q5_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q5_t0.csv /platform/expected/s01/q5.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11122200/m11122200_q5_t0.py", line 24, in <module>
    cursor.execute(mysql_query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.customer' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q6_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q6_t0.csv /platform/expected/s01/q6.csv
>>> Expected ((1, 1))
        REVENUE
0  7.115407e+06

>>> Actual ((1, 1))
   total_revenue
0   1.845191e+08

Head row similarity: 0.375
Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q7_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q7_t0.csv /platform/expected/s01/q7.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11122200/m11122200_q7_t0.py", line 50, in <module>
    supplier_df = pd.read_msgpack(redis_client.get('supplier'))
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q8_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q8_t0.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11122200/m11122200_q8_t0.py", line 37, in <module>
    supplier = pd.read_json(redis_get('supplier').decode('utf-8'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'decode'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11122200/m11122200_q9_t0.py /platform/output/s01/v4_enggpt/m11122200/m11122200_q9_t0.csv /platform/expected/s01/q9.csv
/platform/source/s01/v4_enggpt/m11122200/m11122200_q9_t0.py:35: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  lineitem_orders = pd.read_sql(sql_query, mysql_conn)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.part' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11122200/m11122200_q9_t0.py", line 35, in <module>
    lineitem_orders = pd.read_sql(sql_query, mysql_conn)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 635, in read_sql
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql '
    SELECT
        l.L_ORDERKEY,
        o.O_ORDERDATE,
        l.L_EXTENDEDPRICE,
        l.L_DISCOUNT,
        l.L_QUANTITY,
        o.O_CUSTKEY
    FROM
        lineitem l
    JOIN
        orders o ON l.L_ORDERKEY = o.O_ORDERKEY
    WHERE
        l.L_PARTKEY IN (
            SELECT P_PARTKEY FROM part WHERE P_NAME like '%dim%'
        )
    ': (1146, "Table 'tpch.part' doesn't exist")
Score.fail_execute
