Using MAPPING_STR=12121212, VERSION_DIR=v4_enggpt
Running /platform/source/s01/v4_enggpt/m12121212/m12121212_q10_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]            Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
0% [2 InRelease 5631 B/114 kB 5%]0% [2 InRelease 15.7 kB/114 kB 14%]                                   0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]21% [Waiting for headers]                         Get:5 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 Packages [2804 kB]
21% [5 Packages 5581 B/2804 kB 0%]                                  74% [Waiting for headers]                         Get:6 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe arm64 Packages [1328 kB]
80% [6 Packages 304 kB/1328 kB 23%]80% [5 Packages store 0 B] [6 Packages 333 kB/1328 kB 25%]                                                          99% [5 Packages store 0 B]                          99% [Working]99% [6 Packages store 0 B]                          100% [Working]              Fetched 4246 kB in 2s (2745 kB/s)
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3 set to manually installed.
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
The following additional packages will be installed:
  git-man krb5-locales less libbrotli1 libcbor0.6 libcurl3-gnutls
  liberror-perl libfido2-1 libgssapi-krb5-2 libk5crypto3 libkeyutils1
  libkrb5-3 libkrb5support0 libnghttp2-14 libpsl5 librtmp1 libssh-4 libx11-6
  libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxmuu1 openssh-client
  publicsuffix xauth
Suggested packages:
  gettext-base git-daemon-run | git-daemon-sysvinit git-doc git-el git-email
  git-gui gitk gitweb git-cvs git-mediawiki git-svn krb5-doc krb5-user
  keychain libpam-ssh monkeysphere ssh-askpass
The following NEW packages will be installed:
  git git-man krb5-locales less libbrotli1 libcbor0.6 libcurl3-gnutls
  liberror-perl libfido2-1 libgssapi-krb5-2 libk5crypto3 libkeyutils1
  libkrb5-3 libkrb5support0 libnghttp2-14 libpsl5 librtmp1 libssh-4 libx11-6
  libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxmuu1 openssh-client
  publicsuffix xauth
0 upgraded, 28 newly installed, 0 to remove and 0 not upgraded.
Need to get 8440 kB of archives.
After this operation, 51.0 MB of additional disk space will be used.
0% [Working]            Get:1 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 less arm64 551-1ubuntu0.1 [119 kB]
0% [1 less 9967 B/119 kB 8%]                            2% [Working]            Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 krb5-locales all 1.17-6ubuntu4.4 [11.5 kB]
2% [2 krb5-locales 2645 B/11.5 kB 23%]                                      Get:3 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libcbor0.6 arm64 0.6.0-0ubuntu1 [20.5 kB]
                                      3% [3 libcbor0.6 2502 B/20.5 kB 12%]                                    4% [Waiting for headers]                        Get:4 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libfido2-1 arm64 1.3.1-1ubuntu2 [45.1 kB]
4% [4 libfido2-1 1979 B/45.1 kB 4%]                                   5% [Waiting for headers]                        Get:5 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libkrb5support0 arm64 1.17-6ubuntu4.4 [30.5 kB]
5% [5 libkrb5support0 1937 B/30.5 kB 6%]                                        6% [Waiting for headers]                        Get:6 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libk5crypto3 arm64 1.17-6ubuntu4.4 [80.4 kB]
6% [6 libk5crypto3 0 B/80.4 kB 0%]                                  7% [Waiting for headers]                        Get:7 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libkeyutils1 arm64 1.6-6ubuntu1.1 [10.1 kB]
7% [7 libkeyutils1 2557 B/10.1 kB 25%]                                      8% [Waiting for headers]                        Get:8 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libkrb5-3 arm64 1.17-6ubuntu4.4 [312 kB]
8% [8 libkrb5-3 880 B/312 kB 0%]                                12% [Working]             Get:9 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libgssapi-krb5-2 arm64 1.17-6ubuntu4.4 [113 kB]
12% [9 libgssapi-krb5-2 1219 B/113 kB 1%]                                         13% [Waiting for headers]                         Get:10 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libpsl5 arm64 0.21.0-1ubuntu1 [51.3 kB]
13% [10 libpsl5 2896 B/51.3 kB 6%]                                  15% [Waiting for headers]                         Get:11 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libxau6 arm64 1:1.0.9-0ubuntu1 [7356 B]
15% [11 libxau6 607 B/7356 B 8%]                                15% [Working]             Get:12 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libxdmcp6 arm64 1:1.1.3-0ubuntu1 [10.3 kB]
16% [12 libxdmcp6 10.3 kB/10.3 kB 100%]                                       16% [Working]             Get:13 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libxcb1 arm64 1.14-2 [43.0 kB]
16% [13 libxcb1 2645 B/43.0 kB 6%]                                  17% [Waiting for headers]                         Get:14 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libx11-data all 2:1.6.9-2ubuntu1.6 [114 kB]
17% [14 libx11-data 2844 B/114 kB 3%]                                     19% [Waiting for headers]                         Get:15 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libx11-6 arm64 2:1.6.9-2ubuntu1.6 [554 kB]
19% [15 libx11-6 1499 B/554 kB 0%]                                  25% [Waiting for headers]                         Get:16 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libxext6 arm64 2:1.3.4-0ubuntu1 [27.7 kB]
25% [16 libxext6 3689 B/27.7 kB 13%]                                    26% [Waiting for headers]                         Get:17 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libxmuu1 arm64 2:1.1.3-0ubuntu1 [9772 B]
26% [17 libxmuu1 9772 B/9772 B 100%]                                    27% [Working]             Get:18 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 openssh-client arm64 1:8.2p1-4ubuntu0.9 [636 kB]
27% [18 openssh-client 9357 B/636 kB 1%]                                        34% [Waiting for headers]                         Get:19 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 publicsuffix all 20200303.0012-1 [111 kB]
34% [19 publicsuffix 13.2 kB/111 kB 12%]                                        35% [Waiting for headers]                         Get:20 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 xauth arm64 1:1.1-0ubuntu1 [24.1 kB]
36% [20 xauth 15.1 kB/24.1 kB 63%]                                  36% [Waiting for headers]                         Get:21 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libbrotli1 arm64 1.0.7-6ubuntu0.1 [257 kB]
37% [21 libbrotli1 24.6 kB/257 kB 10%]                                      40% [Waiting for headers]                         Get:22 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libnghttp2-14 arm64 1.40.0-1ubuntu0.2 [75.9 kB]
40% [22 libnghttp2-14 24.6 kB/75.9 kB 32%]                                          41% [Working]             Get:23 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 librtmp1 arm64 2.4+20151223.gitfa8646d.1-2build1 [53.3 kB]
41% [23 librtmp1 14.2 kB/53.3 kB 27%]                                     42% [Working]             Get:24 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libssh-4 arm64 0.9.3-2ubuntu2.3 [160 kB]
42% [24 libssh-4 2643 B/160 kB 2%]                                  44% [Working]             Get:25 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libcurl3-gnutls arm64 7.68.0-1ubuntu2.20 [213 kB]
44% [25 libcurl3-gnutls 466 B/213 kB 0%]                                        47% [Waiting for headers]                         Get:26 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 liberror-perl all 0.17029-1 [26.5 kB]
47% [26 liberror-perl 2829 B/26.5 kB 11%]                                         48% [Waiting for headers]                         Get:27 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 git-man all 1:2.25.1-1ubuntu3.11 [887 kB]
48% [27 git-man 5847 B/887 kB 1%]                                 57% [Waiting for headers]                         Get:28 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 git arm64 1:2.25.1-1ubuntu3.11 [4437 kB]
57% [28 git 0 B/4437 kB 0%]                           100% [Working]              Fetched 8440 kB in 3s (2664 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package less.
(Reading database ... (Reading database ... 5%(Reading database ... 10%(Reading database ... 15%(Reading database ... 20%(Reading database ... 25%(Reading database ... 30%(Reading database ... 35%(Reading database ... 40%(Reading database ... 45%(Reading database ... 50%(Reading database ... 55%(Reading database ... 60%(Reading database ... 65%(Reading database ... 70%(Reading database ... 75%(Reading database ... 80%(Reading database ... 85%(Reading database ... 90%(Reading database ... 95%(Reading database ... 100%(Reading database ... 14446 files and directories currently installed.)
Preparing to unpack .../00-less_551-1ubuntu0.1_arm64.deb ...
Unpacking less (551-1ubuntu0.1) ...
Selecting previously unselected package krb5-locales.
Preparing to unpack .../01-krb5-locales_1.17-6ubuntu4.4_all.deb ...
Unpacking krb5-locales (1.17-6ubuntu4.4) ...
Selecting previously unselected package libcbor0.6:arm64.
Preparing to unpack .../02-libcbor0.6_0.6.0-0ubuntu1_arm64.deb ...
Unpacking libcbor0.6:arm64 (0.6.0-0ubuntu1) ...
Selecting previously unselected package libfido2-1:arm64.
Preparing to unpack .../03-libfido2-1_1.3.1-1ubuntu2_arm64.deb ...
Unpacking libfido2-1:arm64 (1.3.1-1ubuntu2) ...
Selecting previously unselected package libkrb5support0:arm64.
Preparing to unpack .../04-libkrb5support0_1.17-6ubuntu4.4_arm64.deb ...
Unpacking libkrb5support0:arm64 (1.17-6ubuntu4.4) ...
Selecting previously unselected package libk5crypto3:arm64.
Preparing to unpack .../05-libk5crypto3_1.17-6ubuntu4.4_arm64.deb ...
Unpacking libk5crypto3:arm64 (1.17-6ubuntu4.4) ...
Selecting previously unselected package libkeyutils1:arm64.
Preparing to unpack .../06-libkeyutils1_1.6-6ubuntu1.1_arm64.deb ...
Unpacking libkeyutils1:arm64 (1.6-6ubuntu1.1) ...
Selecting previously unselected package libkrb5-3:arm64.
Preparing to unpack .../07-libkrb5-3_1.17-6ubuntu4.4_arm64.deb ...
Unpacking libkrb5-3:arm64 (1.17-6ubuntu4.4) ...
Selecting previously unselected package libgssapi-krb5-2:arm64.
Preparing to unpack .../08-libgssapi-krb5-2_1.17-6ubuntu4.4_arm64.deb ...
Unpacking libgssapi-krb5-2:arm64 (1.17-6ubuntu4.4) ...
Selecting previously unselected package libpsl5:arm64.
Preparing to unpack .../09-libpsl5_0.21.0-1ubuntu1_arm64.deb ...
Unpacking libpsl5:arm64 (0.21.0-1ubuntu1) ...
Selecting previously unselected package libxau6:arm64.
Preparing to unpack .../10-libxau6_1%3a1.0.9-0ubuntu1_arm64.deb ...
Unpacking libxau6:arm64 (1:1.0.9-0ubuntu1) ...
Selecting previously unselected package libxdmcp6:arm64.
Preparing to unpack .../11-libxdmcp6_1%3a1.1.3-0ubuntu1_arm64.deb ...
Unpacking libxdmcp6:arm64 (1:1.1.3-0ubuntu1) ...
Selecting previously unselected package libxcb1:arm64.
Preparing to unpack .../12-libxcb1_1.14-2_arm64.deb ...
Unpacking libxcb1:arm64 (1.14-2) ...
Selecting previously unselected package libx11-data.
Preparing to unpack .../13-libx11-data_2%3a1.6.9-2ubuntu1.6_all.deb ...
Unpacking libx11-data (2:1.6.9-2ubuntu1.6) ...
Selecting previously unselected package libx11-6:arm64.
Preparing to unpack .../14-libx11-6_2%3a1.6.9-2ubuntu1.6_arm64.deb ...
Unpacking libx11-6:arm64 (2:1.6.9-2ubuntu1.6) ...
Selecting previously unselected package libxext6:arm64.
Preparing to unpack .../15-libxext6_2%3a1.3.4-0ubuntu1_arm64.deb ...
Unpacking libxext6:arm64 (2:1.3.4-0ubuntu1) ...
Selecting previously unselected package libxmuu1:arm64.
Preparing to unpack .../16-libxmuu1_2%3a1.1.3-0ubuntu1_arm64.deb ...
Unpacking libxmuu1:arm64 (2:1.1.3-0ubuntu1) ...
Selecting previously unselected package openssh-client.
Preparing to unpack .../17-openssh-client_1%3a8.2p1-4ubuntu0.9_arm64.deb ...
Unpacking openssh-client (1:8.2p1-4ubuntu0.9) ...
Selecting previously unselected package publicsuffix.
Preparing to unpack .../18-publicsuffix_20200303.0012-1_all.deb ...
Unpacking publicsuffix (20200303.0012-1) ...
Selecting previously unselected package xauth.
Preparing to unpack .../19-xauth_1%3a1.1-0ubuntu1_arm64.deb ...
Unpacking xauth (1:1.1-0ubuntu1) ...
Selecting previously unselected package libbrotli1:arm64.
Preparing to unpack .../20-libbrotli1_1.0.7-6ubuntu0.1_arm64.deb ...
Unpacking libbrotli1:arm64 (1.0.7-6ubuntu0.1) ...
Selecting previously unselected package libnghttp2-14:arm64.
Preparing to unpack .../21-libnghttp2-14_1.40.0-1ubuntu0.2_arm64.deb ...
Unpacking libnghttp2-14:arm64 (1.40.0-1ubuntu0.2) ...
Selecting previously unselected package librtmp1:arm64.
Preparing to unpack .../22-librtmp1_2.4+20151223.gitfa8646d.1-2build1_arm64.deb ...
Unpacking librtmp1:arm64 (2.4+20151223.gitfa8646d.1-2build1) ...
Selecting previously unselected package libssh-4:arm64.
Preparing to unpack .../23-libssh-4_0.9.3-2ubuntu2.3_arm64.deb ...
Unpacking libssh-4:arm64 (0.9.3-2ubuntu2.3) ...
Selecting previously unselected package libcurl3-gnutls:arm64.
Preparing to unpack .../24-libcurl3-gnutls_7.68.0-1ubuntu2.20_arm64.deb ...
Unpacking libcurl3-gnutls:arm64 (7.68.0-1ubuntu2.20) ...
Selecting previously unselected package liberror-perl.
Preparing to unpack .../25-liberror-perl_0.17029-1_all.deb ...
Unpacking liberror-perl (0.17029-1) ...
Selecting previously unselected package git-man.
Preparing to unpack .../26-git-man_1%3a2.25.1-1ubuntu3.11_all.deb ...
Unpacking git-man (1:2.25.1-1ubuntu3.11) ...
Selecting previously unselected package git.
Preparing to unpack .../27-git_1%3a2.25.1-1ubuntu3.11_arm64.deb ...
Unpacking git (1:2.25.1-1ubuntu3.11) ...
Setting up libxau6:arm64 (1:1.0.9-0ubuntu1) ...
Setting up libxdmcp6:arm64 (1:1.1.3-0ubuntu1) ...
Setting up libkeyutils1:arm64 (1.6-6ubuntu1.1) ...
Setting up libpsl5:arm64 (0.21.0-1ubuntu1) ...
Setting up libxcb1:arm64 (1.14-2) ...
Setting up libbrotli1:arm64 (1.0.7-6ubuntu0.1) ...
Setting up libnghttp2-14:arm64 (1.40.0-1ubuntu0.2) ...
Setting up less (551-1ubuntu0.1) ...
Setting up krb5-locales (1.17-6ubuntu4.4) ...
Setting up libcbor0.6:arm64 (0.6.0-0ubuntu1) ...
Setting up libkrb5support0:arm64 (1.17-6ubuntu4.4) ...
Setting up liberror-perl (0.17029-1) ...
Setting up libx11-data (2:1.6.9-2ubuntu1.6) ...
Setting up librtmp1:arm64 (2.4+20151223.gitfa8646d.1-2build1) ...
Setting up libk5crypto3:arm64 (1.17-6ubuntu4.4) ...
Setting up git-man (1:2.25.1-1ubuntu3.11) ...
Setting up libx11-6:arm64 (2:1.6.9-2ubuntu1.6) ...
Setting up libkrb5-3:arm64 (1.17-6ubuntu4.4) ...
Setting up libfido2-1:arm64 (1.3.1-1ubuntu2) ...
Setting up publicsuffix (20200303.0012-1) ...
Setting up libxmuu1:arm64 (2:1.1.3-0ubuntu1) ...
Setting up libxext6:arm64 (2:1.3.4-0ubuntu1) ...
Setting up libgssapi-krb5-2:arm64 (1.17-6ubuntu4.4) ...
Setting up libssh-4:arm64 (0.9.3-2ubuntu2.3) ...
Setting up xauth (1:1.1-0ubuntu1) ...
Setting up openssh-client (1:8.2p1-4ubuntu0.9) ...
Setting up libcurl3-gnutls:arm64 (7.68.0-1ubuntu2.20) ...
Setting up git (1:2.25.1-1ubuntu3.11) ...
Processing triggers for libc-bin (2.31-0ubuntu9.12) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Running /platform/source/s01/v4_enggpt/m12121212/m12121212_q11_t0.sh
/platform/source/s01/v4_enggpt/m12121212/m12121212_q11_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_enggpt/m12121212/m12121212_q11_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_enggpt/m12121212/m12121212_q12_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
Calculating upgrade... 0%Calculating upgrade... 50%Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_enggpt/m12121212/m12121212_q13_t0.sh
/platform/source/s01/v4_enggpt/m12121212/m12121212_q13_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_enggpt/m12121212/m12121212_q13_t0.sh: line 6: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_enggpt/m12121212/m12121212_q14_t0.sh
/platform/source/s01/v4_enggpt/m12121212/m12121212_q14_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m12121212/m12121212_q14_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Running /platform/source/s01/v4_enggpt/m12121212/m12121212_q15_t0.sh
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

/platform/source/s01/v4_enggpt/m12121212/m12121212_q15_t0.sh: line 8: venv/bin/activate: No such file or directory
Collecting pip
  Downloading pip-23.3.1-py3-none-any.whl (2.1 MB)
[?25l[K     |▏                               | 10 kB 41.5 MB/s eta 0:00:01[K     |▎                               | 20 kB 2.8 MB/s eta 0:00:01[K     |▌                               | 30 kB 4.1 MB/s eta 0:00:01[K     |▋                               | 40 kB 3.1 MB/s eta 0:00:01[K     |▊                               | 51 kB 2.7 MB/s eta 0:00:01[K     |█                               | 61 kB 3.2 MB/s eta 0:00:01[K     |█                               | 71 kB 3.7 MB/s eta 0:00:01[K     |█▎                              | 81 kB 3.9 MB/s eta 0:00:01[K     |█▍                              | 92 kB 4.4 MB/s eta 0:00:01[K     |█▌                              | 102 kB 3.9 MB/s eta 0:00:01[K     |█▊                              | 112 kB 3.9 MB/s eta 0:00:01[K     |█▉                              | 122 kB 3.9 MB/s eta 0:00:01[K     |██                              | 133 kB 3.9 MB/s eta 0:00:01[K     |██▏                             | 143 kB 3.9 MB/s eta 0:00:01[K     |██▎                             | 153 kB 3.9 MB/s eta 0:00:01[K     |██▌                             | 163 kB 3.9 MB/s eta 0:00:01[K     |██▋                             | 174 kB 3.9 MB/s eta 0:00:01[K     |██▉                             | 184 kB 3.9 MB/s eta 0:00:01[K     |███                             | 194 kB 3.9 MB/s eta 0:00:01[K     |███                             | 204 kB 3.9 MB/s eta 0:00:01[K     |███▎                            | 215 kB 3.9 MB/s eta 0:00:01[K     |███▍                            | 225 kB 3.9 MB/s eta 0:00:01[K     |███▋                            | 235 kB 3.9 MB/s eta 0:00:01[K     |███▊                            | 245 kB 3.9 MB/s eta 0:00:01[K     |███▉                            | 256 kB 3.9 MB/s eta 0:00:01[K     |████                            | 266 kB 3.9 MB/s eta 0:00:01[K     |████▏                           | 276 kB 3.9 MB/s eta 0:00:01[K     |████▍                           | 286 kB 3.9 MB/s eta 0:00:01[K     |████▌                           | 296 kB 3.9 MB/s eta 0:00:01[K     |████▋                           | 307 kB 3.9 MB/s eta 0:00:01[K     |████▉                           | 317 kB 3.9 MB/s eta 0:00:01[K     |█████                           | 327 kB 3.9 MB/s eta 0:00:01[K     |█████▏                          | 337 kB 3.9 MB/s eta 0:00:01[K     |█████▎                          | 348 kB 3.9 MB/s eta 0:00:01[K     |█████▍                          | 358 kB 3.9 MB/s eta 0:00:01[K     |█████▋                          | 368 kB 3.9 MB/s eta 0:00:01[K     |█████▊                          | 378 kB 3.9 MB/s eta 0:00:01[K     |██████                          | 389 kB 3.9 MB/s eta 0:00:01[K     |██████                          | 399 kB 3.9 MB/s eta 0:00:01[K     |██████▏                         | 409 kB 3.9 MB/s eta 0:00:01[K     |██████▍                         | 419 kB 3.9 MB/s eta 0:00:01[K     |██████▌                         | 430 kB 3.9 MB/s eta 0:00:01[K     |██████▊                         | 440 kB 3.9 MB/s eta 0:00:01[K     |██████▉                         | 450 kB 3.9 MB/s eta 0:00:01[K     |███████                         | 460 kB 3.9 MB/s eta 0:00:01[K     |███████▏                        | 471 kB 3.9 MB/s eta 0:00:01[K     |███████▎                        | 481 kB 3.9 MB/s eta 0:00:01[K     |███████▌                        | 491 kB 3.9 MB/s eta 0:00:01[K     |███████▋                        | 501 kB 3.9 MB/s eta 0:00:01[K     |███████▊                        | 512 kB 3.9 MB/s eta 0:00:01[K     |████████                        | 522 kB 3.9 MB/s eta 0:00:01[K     |████████                        | 532 kB 3.9 MB/s eta 0:00:01[K     |████████▎                       | 542 kB 3.9 MB/s eta 0:00:01[K     |████████▍                       | 552 kB 3.9 MB/s eta 0:00:01[K     |████████▌                       | 563 kB 3.9 MB/s eta 0:00:01[K     |████████▊                       | 573 kB 3.9 MB/s eta 0:00:01[K     |████████▉                       | 583 kB 3.9 MB/s eta 0:00:01[K     |█████████                       | 593 kB 3.9 MB/s eta 0:00:01[K     |█████████▏                      | 604 kB 3.9 MB/s eta 0:00:01[K     |█████████▎                      | 614 kB 3.9 MB/s eta 0:00:01[K     |█████████▌                      | 624 kB 3.9 MB/s eta 0:00:01[K     |█████████▋                      | 634 kB 3.9 MB/s eta 0:00:01[K     |█████████▉                      | 645 kB 3.9 MB/s eta 0:00:01[K     |██████████                      | 655 kB 3.9 MB/s eta 0:00:01[K     |██████████                      | 665 kB 3.9 MB/s eta 0:00:01[K     |██████████▎                     | 675 kB 3.9 MB/s eta 0:00:01[K     |██████████▍                     | 686 kB 3.9 MB/s eta 0:00:01[K     |██████████▋                     | 696 kB 3.9 MB/s eta 0:00:01[K     |██████████▊                     | 706 kB 3.9 MB/s eta 0:00:01[K     |██████████▉                     | 716 kB 3.9 MB/s eta 0:00:01[K     |███████████                     | 727 kB 3.9 MB/s eta 0:00:01[K     |███████████▏                    | 737 kB 3.9 MB/s eta 0:00:01[K     |███████████▍                    | 747 kB 3.9 MB/s eta 0:00:01[K     |███████████▌                    | 757 kB 3.9 MB/s eta 0:00:01[K     |███████████▋                    | 768 kB 3.9 MB/s eta 0:00:01[K     |███████████▉                    | 778 kB 3.9 MB/s eta 0:00:01[K     |████████████                    | 788 kB 3.9 MB/s eta 0:00:01[K     |████████████▏                   | 798 kB 3.9 MB/s eta 0:00:01[K     |████████████▎                   | 808 kB 3.9 MB/s eta 0:00:01[K     |████████████▍                   | 819 kB 3.9 MB/s eta 0:00:01[K     |████████████▋                   | 829 kB 3.9 MB/s eta 0:00:01[K     |████████████▊                   | 839 kB 3.9 MB/s eta 0:00:01[K     |█████████████                   | 849 kB 3.9 MB/s eta 0:00:01[K     |█████████████                   | 860 kB 3.9 MB/s eta 0:00:01[K     |█████████████▏                  | 870 kB 3.9 MB/s eta 0:00:01[K     |█████████████▍                  | 880 kB 3.9 MB/s eta 0:00:01[K     |█████████████▌                  | 890 kB 3.9 MB/s eta 0:00:01[K     |█████████████▊                  | 901 kB 3.9 MB/s eta 0:00:01[K     |█████████████▉                  | 911 kB 3.9 MB/s eta 0:00:01[K     |██████████████                  | 921 kB 3.9 MB/s eta 0:00:01[K     |██████████████▏                 | 931 kB 3.9 MB/s eta 0:00:01[K     |██████████████▎                 | 942 kB 3.9 MB/s eta 0:00:01[K     |██████████████▌                 | 952 kB 3.9 MB/s eta 0:00:01[K     |██████████████▋                 | 962 kB 3.9 MB/s eta 0:00:01[K     |██████████████▊                 | 972 kB 3.9 MB/s eta 0:00:01[K     |███████████████                 | 983 kB 3.9 MB/s eta 0:00:01[K     |███████████████                 | 993 kB 3.9 MB/s eta 0:00:01[K     |███████████████▎                | 1.0 MB 3.9 MB/s eta 0:00:01[K     |███████████████▍                | 1.0 MB 3.9 MB/s eta 0:00:01[K     |███████████████▌                | 1.0 MB 3.9 MB/s eta 0:00:01[K     |███████████████▊                | 1.0 MB 3.9 MB/s eta 0:00:01[K     |███████████████▉                | 1.0 MB 3.9 MB/s eta 0:00:01[K     |████████████████                | 1.1 MB 3.9 MB/s eta 0:00:01[K     |████████████████▏               | 1.1 MB 3.9 MB/s eta 0:00:01[K     |████████████████▎               | 1.1 MB 3.9 MB/s eta 0:00:01[K     |████████████████▌               | 1.1 MB 3.9 MB/s eta 0:00:01[K     |████████████████▋               | 1.1 MB 3.9 MB/s eta 0:00:01[K     |████████████████▉               | 1.1 MB 3.9 MB/s eta 0:00:01[K     |█████████████████               | 1.1 MB 3.9 MB/s eta 0:00:01[K     |█████████████████               | 1.1 MB 3.9 MB/s eta 0:00:01[K     |█████████████████▎              | 1.1 MB 3.9 MB/s eta 0:00:01[K     |█████████████████▍              | 1.1 MB 3.9 MB/s eta 0:00:01[K     |█████████████████▋              | 1.2 MB 3.9 MB/s eta 0:00:01[K     |█████████████████▊              | 1.2 MB 3.9 MB/s eta 0:00:01[K     |█████████████████▉              | 1.2 MB 3.9 MB/s eta 0:00:01[K     |██████████████████              | 1.2 MB 3.9 MB/s eta 0:00:01[K     |██████████████████▏             | 1.2 MB 3.9 MB/s eta 0:00:01[K     |██████████████████▍             | 1.2 MB 3.9 MB/s eta 0:00:01[K     |██████████████████▌             | 1.2 MB 3.9 MB/s eta 0:00:01[K     |██████████████████▋             | 1.2 MB 3.9 MB/s eta 0:00:01[K     |██████████████████▉             | 1.2 MB 3.9 MB/s eta 0:00:01[K     |███████████████████             | 1.2 MB 3.9 MB/s eta 0:00:01[K     |███████████████████▏            | 1.3 MB 3.9 MB/s eta 0:00:01[K     |███████████████████▎            | 1.3 MB 3.9 MB/s eta 0:00:01[K     |███████████████████▍            | 1.3 MB 3.9 MB/s eta 0:00:01[K     |███████████████████▋            | 1.3 MB 3.9 MB/s eta 0:00:01[K     |███████████████████▊            | 1.3 MB 3.9 MB/s eta 0:00:01[K     |████████████████████            | 1.3 MB 3.9 MB/s eta 0:00:01[K     |████████████████████            | 1.3 MB 3.9 MB/s eta 0:00:01[K     |████████████████████▏           | 1.3 MB 3.9 MB/s eta 0:00:01[K     |████████████████████▍           | 1.3 MB 3.9 MB/s eta 0:00:01[K     |████████████████████▌           | 1.4 MB 3.9 MB/s eta 0:00:01[K     |████████████████████▊           | 1.4 MB 3.9 MB/s eta 0:00:01[K     |████████████████████▉           | 1.4 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████           | 1.4 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████▏          | 1.4 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████▎          | 1.4 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████▌          | 1.4 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████▋          | 1.4 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████▊          | 1.4 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████          | 1.4 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████          | 1.5 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████▎         | 1.5 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████▍         | 1.5 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████▌         | 1.5 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████▊         | 1.5 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████▉         | 1.5 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████         | 1.5 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████▏        | 1.5 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████▎        | 1.5 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████▌        | 1.5 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████▋        | 1.6 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████▉        | 1.6 MB 3.9 MB/s eta 0:00:01[K     |████████████████████████        | 1.6 MB 3.9 MB/s eta 0:00:01[K     |████████████████████████        | 1.6 MB 3.9 MB/s eta 0:00:01[K     |████████████████████████▎       | 1.6 MB 3.9 MB/s eta 0:00:01[K     |████████████████████████▍       | 1.6 MB 3.9 MB/s eta 0:00:01[K     |████████████████████████▋       | 1.6 MB 3.9 MB/s eta 0:00:01[K     |████████████████████████▊       | 1.6 MB 3.9 MB/s eta 0:00:01[K     |████████████████████████▉       | 1.6 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████████       | 1.6 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████████▏      | 1.7 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████████▍      | 1.7 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████████▌      | 1.7 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████████▋      | 1.7 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████████▉      | 1.7 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████████      | 1.7 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████████▏     | 1.7 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████████▎     | 1.7 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████████▍     | 1.7 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████████▋     | 1.8 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████████▊     | 1.8 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████████     | 1.8 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████████     | 1.8 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████████▏    | 1.8 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████████▍    | 1.8 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████████▌    | 1.8 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████████▊    | 1.8 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████████▉    | 1.8 MB 3.9 MB/s eta 0:00:01[K     |████████████████████████████    | 1.8 MB 3.9 MB/s eta 0:00:01[K     |████████████████████████████▏   | 1.9 MB 3.9 MB/s eta 0:00:01[K     |████████████████████████████▎   | 1.9 MB 3.9 MB/s eta 0:00:01[K     |████████████████████████████▌   | 1.9 MB 3.9 MB/s eta 0:00:01[K     |████████████████████████████▋   | 1.9 MB 3.9 MB/s eta 0:00:01[K     |████████████████████████████▊   | 1.9 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████████████   | 1.9 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████████████   | 1.9 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████████████▎  | 1.9 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████████████▍  | 1.9 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████████████▌  | 1.9 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████████████▊  | 2.0 MB 3.9 MB/s eta 0:00:01[K     |█████████████████████████████▉  | 2.0 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████████████  | 2.0 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████████████▏ | 2.0 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████████████▎ | 2.0 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████████████▌ | 2.0 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████████████▋ | 2.0 MB 3.9 MB/s eta 0:00:01[K     |██████████████████████████████▉ | 2.0 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████████████ | 2.0 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████████████ | 2.0 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████████████▎| 2.1 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████████████▍| 2.1 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████████████▋| 2.1 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████████████▊| 2.1 MB 3.9 MB/s eta 0:00:01[K     |███████████████████████████████▉| 2.1 MB 3.9 MB/s eta 0:00:01[K     |████████████████████████████████| 2.1 MB 3.9 MB/s 
[?25hInstalling collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-23.3.1
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_enggpt/m12121212/m12121212_q16_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m12121212/m12121212_q17_t0.sh
/platform/source/s01/v4_enggpt/m12121212/m12121212_q17_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m12121212/m12121212_q17_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m12121212/m12121212_q18_t0.sh
/platform/source/s01/v4_enggpt/m12121212/m12121212_q18_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m12121212/m12121212_q18_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_enggpt/m12121212/m12121212_q18_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m12121212/m12121212_q19_t0.sh
/platform/source/s01/v4_enggpt/m12121212/m12121212_q19_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_enggpt/m12121212/m12121212_q19_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4_enggpt/m12121212/m12121212_q19_t0.sh: line 9: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m12121212/m12121212_q1_t0.sh
/platform/source/s01/v4_enggpt/m12121212/m12121212_q1_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m12121212/m12121212_q1_t0.sh: line 7: sudo: command not found
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m12121212/m12121212_q20_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mInstalling DirectRedis...
Cloning into 'direct_redis'...
Username for 'https://github.com': m
Password for 'https://m@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/some-repo/direct_redis.git/'
/platform/source/s01/v4_enggpt/m12121212/m12121212_q20_t0.sh: line 17: cd: direct_redis: No such file or directory
python3: can't open file 'setup.py': [Errno 2] No such file or directory
Running /platform/source/s01/v4_enggpt/m12121212/m12121212_q21_t0.sh
/platform/source/s01/v4_enggpt/m12121212/m12121212_q21_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_enggpt/m12121212/m12121212_q21_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m12121212/m12121212_q22_t0.sh
/platform/source/s01/v4_enggpt/m12121212/m12121212_q22_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m12121212/m12121212_q22_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m12121212/m12121212_q2_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m12121212/m12121212_q3_t0.sh
/platform/source/s01/v4_enggpt/m12121212/m12121212_q3_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m12121212/m12121212_q3_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m12121212/m12121212_q4_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m12121212/m12121212_q5_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m12121212/m12121212_q6_t0.sh
/platform/source/s01/v4_enggpt/m12121212/m12121212_q6_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m12121212/m12121212_q6_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_enggpt/m12121212/m12121212_q6_t0.sh: line 6: sudo: command not found
Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (23.3.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m12121212/m12121212_q7_t0.sh
/platform/source/s01/v4_enggpt/m12121212/m12121212_q7_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m12121212/m12121212_q7_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m12121212/m12121212_q8_t0.sh
Running /platform/source/s01/v4_enggpt/m12121212/m12121212_q9_t0.sh
/platform/source/s01/v4_enggpt/m12121212/m12121212_q9_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4_enggpt/m12121212/m12121212_q9_t0.sh: line 9: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mpython /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q10_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q10_t0.csv /platform/expected/s01/q10.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q10_t0.py", line 18, in <module>
    df_customer = pd.read_json(redis_client.get('customer'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q11_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q11_t0.csv /platform/expected/s01/q11.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q11_t0.py", line 25, in <module>
    supplier_data = get_redis_table_data('supplier')
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q11_t0.py", line 17, in get_redis_table_data
    data = pd.read_json(redis_client.get(key_name))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q12_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q12_t0.csv /platform/expected/s01/q12.csv
>>> Expected ((2, 3))
   HIGH_LINE_COUNT  LOW_LINE_COUNT L_SHIPMODE
0              647             945       MAIL
1              620             943       SHIP

>>> Actual ((2, 3))
   HIGH_LINE_COUNT  LOW_LINE_COUNT SHIP_MODE
0                0           10322      MAIL
1                0           10373      SHIP

Head row similarity: 0.8782287822878229
Score.success_approx
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q13_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q13_t0.csv /platform/expected/s01/q13.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q13_t0.py", line 28, in <module>
    customer_df = pd.read_json(customer_data).rename(columns={'C_CUSTKEY': 'CUSTKEY'})
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q14_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q14_t0.csv /platform/expected/s01/q14.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q14_t0.py", line 15, in <module>
    redis_client = direct_redis.DirectRedis(host='redis', port=6379, db=0)
AttributeError: module 'redis' has no attribute 'DirectRedis'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q15_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q15_t0.csv /platform/expected/s01/q15.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q15_t0.py", line 10, in <module>
    supplier_df = pd.read_json(r.get('supplier'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q16_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q16_t0.csv /platform/expected/s01/q16.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q16_t0.py", line 35, in <module>
    df_supplier = pd.read_json(supplier_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q17_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q17_t0.csv /platform/expected/s01/q17.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q17_t0.py", line 19, in <module>
    lineitem_df = pd.read_json(lineitem_table, orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q18_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q18_t0.csv /platform/expected/s01/q18.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q18_t0.py", line 17, in <module>
    customers_df = pd.read_json(redis_client.get('customer').decode('utf-8'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'decode'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q19_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q19_t0.csv /platform/expected/s01/q19.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q19_t0.py", line 18, in <module>
    lineitem = pd.read_json(r.get('lineitem'), orient='records')
  File "/usr/local/lib/python3.8/dist-packages/redis/client.py", line 1579, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.8/dist-packages/redis/client.py", line 878, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.8/dist-packages/redis/client.py", line 892, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 734, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 358, in read_response
    response = self.encoder.decode(response)
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 129, in decode
    value = value.decode(self.encoding, self.encoding_errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q1_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q1_t0.csv /platform/expected/s01/q1.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q1_t0.py", line 14, in <module>
    lineitem_df = pd.read_json(lineitem_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q20_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q20_t0.csv /platform/expected/s01/q20.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q20_t0.py", line 24, in <module>
    supplier_df = pd.read_json(redis_client.get('supplier'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q21_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q21_t0.csv /platform/expected/s01/q21.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q21_t0.py", line 17, in <module>
    supplier_df = pd.read_json(r.get('supplier'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q22_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q22_t0.csv /platform/expected/s01/q22.csv
Error retrieving customer data from Redis: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q22_t0.py", line 24, in <module>
    customer_df['CNTRYCODE'] = customer_df['C_PHONE'].str[:2]
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/range.py", line 349, in get_loc
    raise KeyError(key)
KeyError: 'C_PHONE'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q2_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q2_t0.csv /platform/expected/s01/q2.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q2_t0.py", line 17, in <module>
    region_df = pd.read_msgpack(redis_client.get('region'))
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q3_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q3_t0.csv /platform/expected/s01/q3.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q3_t0.py", line 26, in <module>
    customer_df = pd.read_json(redis_client.get('customer'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q4_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q4_t0.csv /platform/expected/s01/q4.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q4_t0.py", line 35, in <module>
    redis_client = DirectRedis(host=redis_host, port=redis_port, db=int(redis_db_name))
NameError: name 'redis_db_name' is not defined
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q5_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q5_t0.csv /platform/expected/s01/q5.csv
>>> Expected ((5, 2))
      N_NAME       REVENUE
0      CHINA  2.094870e+07
1  INDONESIA  1.765375e+07
2      INDIA  1.758996e+07
3      JAPAN  1.634845e+07
4    VIETNAM  1.433735e+07

>>> Actual ((5, 2))
      N_NAME  TOTAL_REVENUE
0  INDONESIA   3.986450e+08
1      CHINA   3.890900e+08
2    VIETNAM   3.752908e+08
3      INDIA   3.567354e+08
4      JAPAN   3.544669e+08

Head row similarity: 0.5
Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q6_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q6_t0.csv /platform/expected/s01/q6.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q6_t0.py", line 41, in <module>
    lineitem_df = get_redis_dataframe(redis_client, 'lineitem')
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q6_t0.py", line 6, in get_redis_dataframe
    return pd.read_json(redis_client.get(table_name), orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q7_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q7_t0.csv /platform/expected/s01/q7.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q7_t0.py", line 24, in <module>
    supplier_df = redis_to_df('supplier')
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q7_t0.py", line 16, in redis_to_df
    df = pd.read_json(data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q8_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q8_t0.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q8_t0.py", line 27, in <module>
    region = pd.read_json(region_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m12121212/m12121212_q9_t0.py /platform/output/s01/v4_enggpt/m12121212/m12121212_q9_t0.csv /platform/expected/s01/q9.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q9_t0.py", line 40, in <module>
    redis_data = get_redis_data()
  File "/platform/source/s01/v4_enggpt/m12121212/m12121212_q9_t0.py", line 32, in get_redis_data
    redis_dfs[key] = pd.read_json(r.get(key))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
